checkpoint with lots of fixes for bootstrap

diff --git a/bin/check_syntax b/bin/check_syntax
--- a/bin/check_syntax
+++ b/bin/check_syntax
@@ -10,7 +10,7 @@ function usage {
 }
 
 if [ "$1" == "all" ]; then
-	files=$(find $__BASE__ -type f) || { echo "was unable to find files, find said: $files"; exit 1; }
+	files=$(find $__BASE__ -type f -name "syntax.pp" ) || { echo "was unable to find files, find said: $files"; exit 1; }
 	echo "checking sytnax of all files"
 elif [ ! -z "$1" ]; then
 	files=$@
@@ -23,7 +23,7 @@ echo "------------"
 
 status=0
 
-for plugin in $__BASE__/bin/syntax.plugins/*.plugin; do
+for plugin in $__BASE__/puppet.wrenchies.net/bin/syntax.plugins/*.plugin; do
 	[ ! -x "$plugin" ] && continue
 	fileName=${plugin##*/}
 	pluginName=${fileName%.plugin}
